### ISSUE TITLE
Tool 'ui_plus.opencv' already exists!

### ISSUE THREAD

**Issue by vardhan-siramdasu** [uhlik/bpy#59]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\vincent.blend\OpenCVAnim.py", line 24, in <module>
  File "C:\Users\Admin\Desktop\vincent.blend\OpenCVAnim.py", line 18, in register
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\utils\__init__.py", line 849, in register_tool
    raise Exception("Tool %r already exists!" % tool_cls.bl_idname)
Exception: Tool 'ui_plus.opencv' already exists!
Error: Python script failed, check the message in the system console

**Comment by uhlik** [comment]
bpy is python module in blender and also it is happen to be name of this repository of blender scripts, but those two are not the same. i guess this line `Exception: Tool 'ui_plus.opencv' already exists!` says it all
